### ISSUE TITLE
[test] Unit Tests in TravisCI

### ISSUE THREAD

**Issue by Cosciad** [nanvix/hal#508]
### Description

We should make TravisCI automatically run regression tests and parse results.

### Roadmap 

- [x] Unix 64-bit (296436fde61e52524247f596a18af4a389f9749e)
- [x] MPPA-256 (ccbb39b17c17666a82234dd37b55ff14fc03eb47)
- [x] Qemu OpenRISC (296436fde61e52524247f596a18af4a389f9749e)
- [x] Qemu RISC-V 32-bit (ccbb39b17c17666a82234dd37b55ff14fc03eb47)
